export const phase = [
    {"word": "compensation", "phrase": "fair compensation package"},
    {"word": "incentive", "phrase": "performance incentive plan"},
    {"word": "commission", "phrase": "sales commission rate"},
    {"word": "allowance", "phrase": "travel allowance policy"},
    {"word": "raise", "phrase": "annual salary raise"},
    {"word": "transfer", "phrase": "interdepartmental transfer"},
    {"word": "demotion", "phrase": "official demotion notice"},
    {"word": "appraisal", "phrase": "employee performance appraisal"},
    {"word": "goal", "phrase": "set annual work goal"},
    {"word": "target", "phrase": "sales target achievement"},
    {"word": "objective", "phrase": "clear business objective"},
    {"word": "achievement", "phrase": "key project achievement"},
    {"word": "accomplishment", "phrase": "major career accomplishment"},
    {"word": "skill", "phrase": "practical work skill"},
    {"word": "ability", "phrase": "problem-solving ability"},
    {"word": "competence", "phrase": "core professional competence"},
    {"word": "faculty", "phrase": "specialized faculty team"},
    {"word": "expertise", "phrase": "technical expertise support"},
    {"word": "proficiency", "phrase": "language proficiency test"},
    {"word": "qualification", "phrase": "job qualification requirement"},
    {"word": "credential", "phrase": "professional credential certificate"},
    {"word": "certificate", "phrase": "training completion certificate"},
    {"word": "license", "phrase": "professional operation license"},
    {"word": "degree", "phrase": "bachelor's degree diploma"},
    {"word": "diploma", "phrase": "vocational training diploma"},
    {"word": "training", "phrase": "on-the-job training course"},
    {"word": "course", "phrase": "online business course"},
    {"word": "program", "phrase": "leadership development program"},
    {"word": "seminar", "phrase": "industry seminar event"},
    {"word": "workshop", "phrase": "team building workshop"},
    {"word": "mentorship", "phrase": "one-on-one mentorship program"},
    {"word": "coaching", "phrase": "executive coaching service"},
    {"word": "guidance", "phrase": "professional guidance advice"},
    {"word": "support", "phrase": "colleague work support"},
    {"word": "development", "phrase": "career development plan"},
    {"word": "growth", "phrase": "company growth strategy"},
    {"word": "progress", "phrase": "weekly work progress report"},
    {"word": "potential", "phrase": "hidden employee potential"},
    {"word": "aspiration", "phrase": "career aspiration goal"},
    {"word": "ambition", "phrase": "leadership ambition drive"},
    {"word": "motivation", "phrase": "work motivation factor"},
    {"word": "initiative", "phrase": "take personal initiative"},
    {"word": "leadership", "phrase": "effective leadership skill"},
    {"word": "teamwork", "phrase": "strong teamwork spirit"},
    {"word": "collaboration", "phrase": "cross-department collaboration"},
    {"word": "communication", "phrase": "clear communication skill"},
    {"word": "interpersonal", "phrase": "interpersonal relationship skill"},
    {"word": "organizational", "phrase": "organizational management ability"},
    {"word": "time-management", "phrase": "time-management skill training"},
    {"word": "problem-solving", "phrase": "problem-solving strategy"},
    {"word": "decision-making", "phrase": "quick decision-making ability"},
    {"word": "adaptability", "phrase": "work environment adaptability"},
    {"word": "flexibility", "phrase": "work schedule flexibility"},
    {"word": "creativity", "phrase": "work creativity improvement"},
    {"word": "innovation", "phrase": "product innovation design"},
    {"word": "critical-thinking", "phrase": "critical-thinking training"},
    {"word": "attention-to-detail", "phrase": "attention-to-detail focus"},
    {"word": "punctuality", "phrase": "work punctuality habit"},
    {"word": "reliability", "phrase": "employee reliability rating"},
    {"word": "responsibility", "phrase": "job responsibility list"},
    {"word": "accountability", "phrase": "work accountability principle"},
    {"word": "integrity", "phrase": "professional integrity standard"},
    {"word": "ethics", "phrase": "business ethics guideline"},
    {"word": "professionalism", "phrase": "workplace professionalism spirit"},
    {"word": "conduct", "phrase": "employee code of conduct"},
    {"word": "behavior", "phrase": "appropriate workplace behavior"},
    {"word": "attitude", "phrase": "positive work attitude"},
    {"word": "demeanor", "phrase": "professional business demeanor"},
    {"word": "appearance", "phrase": "neat workplace appearance"},
    {"word": "etiquette", "phrase": "business etiquette training"},
    {"word": "protocol", "phrase": "official meeting protocol"},
    {"word": "manners", "phrase": "polite business manners"},
    {"word": "courtesy", "phrase": "workplace courtesy rule"},
    {"word": "respect", "phrase": "mutual colleague respect"},
    {"word": "courteous", "phrase": "courteous customer service"},
    {"word": "polite", "phrase": "polite communication style"},
    {"word": "appropriate", "phrase": "appropriate work attire"},
    {"word": "suitable", "phrase": "suitable candidate choice"},
    {"word": "fit", "phrase": "job role fitness assessment"},
    {"word": "compatible", "phrase": "team compatible member"},
    {"word": "harmonious", "phrase": "harmonious work environment"},
    {"word": "productive", "phrase": "productive work efficiency"},
    {"word": "efficient", "phrase": "efficient work method"},
    {"word": "effective", "phrase": "effective solution strategy"},
    {"word": "successful", "phrase": "successful project completion"},
    {"word": "improvement", "phrase": "work efficiency improvement"},
    {"word": "enhancement", "phrase": "skill enhancement training"},
    {"word": "advancement", "phrase": "career advancement opportunity"},
    {"word": "elevation", "phrase": "position elevation notice"},
    {"word": "rise", "phrase": "steady career rise"},
    {"word": "upgrade", "phrase": "system software upgrade"},
    {"word": "betterment", "phrase": "workplace betterment plan"},
    {"word": "refinement", "phrase": "process refinement measure"},
    {"word": "perfection", "phrase": "pursuit of work perfection"},
    {"word": "excellence", "phrase": "culture of excellence"},
    {"word": "superiority", "phrase": "product quality superiority"},
    {"word": "quality", "phrase": "high work quality standard"},
    {"word": "standard", "phrase": "industry standard compliance"},
    {"word": "level", "phrase": "skill level assessment"},
    {"word": "grade", "phrase": "performance grade rating"},
    {"word": "rank", "phrase": "employee rank promotion"},
    {"word": "position", "phrase": "senior management position"},
    {"word": "status", "phrase": "professional social status"},
    {"word": "role", "phrase": "key project team role"},
    {"word": "job", "phrase": "stable full-time job"},
    {"word": "occupation", "phrase": "respected professional occupation"},
    {"word": "profession", "phrase": "medical profession ethics"},
    {"word": "vocation", "phrase": "lifelong career vocation"},
    {"word": "calling", "phrase": "leadership career calling"},
    {"word": "employment", "phrase": "stable employment opportunity"},
    {"word": "work", "phrase": "daily routine work task"},
    {"word": "labor", "phrase": "skilled labor force"},
    {"word": "task", "phrase": "urgent work task"},
    {"word": "duty", "phrase": "employee core duty"},
    {"word": "obligation", "phrase": "legal work obligation"},
    {"word": "assignment", "phrase": "special project assignment"},
    {"word": "project", "phrase": "long-term business project"},
    {"word": "mission", "phrase": "company core mission"},
    {"word": "aim", "phrase": "clear business aim"},
    {"word": "purpose", "phrase": "project main purpose"},
    {"word": "intention", "phrase": "clear work intention"},
    {"word": "desire", "phrase": "career development desire"},
    {"word": "wish", "phrase": "work goal wish list"},
    {"word": "hope", "phrase": "career promotion hope"},
    {"word": "expectation", "phrase": "manager work expectation"},
    {"word": "anticipation", "phrase": "project result anticipation"},
    {"word": "plan", "phrase": "detailed business plan"},
    {"word": "strategy", "phrase": "company marketing strategy"},
    {"word": "tactic", "phrase": "sales promotion tactic"},
    {"word": "method", "phrase": "efficient work method"},
    {"word": "approach", "phrase": "innovative problem approach"},
    {"word": "way", "phrase": "simple working way"},
    {"word": "means", "phrase": "effective solution means"},
    {"word": "technique", "phrase": "advanced production technique"},
    {"word": "procedure", "phrase": "standard operation procedure"},
    {"word": "process", "phrase": "streamline work process"},
    {"word": "system", "phrase": "company management system"},
    {"word": "scheme", "phrase": "business expansion scheme"},
    {"word": "campaign", "phrase": "product marketing campaign"},
    {"word": "effort", "phrase": "team joint effort"},
    {"word": "endeavor", "phrase": "career development endeavor"},
    {"word": "attempt", "phrase": "new method attempt"},
    {"word": "try", "phrase": "first trial try"},
    {"word": "experiment", "phrase": "product development experiment"},
    {"word": "venture", "phrase": "business investment venture"},
    {"word": "undertaking", "phrase": "large-scale business undertaking"},
    {"word": "enterprise", "phrase": "innovative business enterprise"},
    {"word": "activity", "phrase": "team building activity"},
    {"word": "action", "phrase": "emergency response action"},
    {"word": "operation", "phrase": "daily company operation"},
    {"word": "function", "phrase": "system core function"},
    {"word": "candidate", "phrase": "a qualified job candidate"},
    {"word": "apprentice", "phrase": "a factory apprentice"},
    {"word": "resume", "phrase": "submit a detailed resume"},
    {"word": "hire", "phrase": "hire a skilled employee"},
    {"word": "recruit", "phrase": "recruit new staff"},
    {"word": "promote", "phrase": "promote to manager"},
    {"word": "performance", "phrase": "annual performance review"},
    {"word": "eligible", "phrase": "eligible for bonus"},
    {"word": "qualified", "phrase": "qualified for the role"},
    {"word": "mentor", "phrase": "a professional mentor"},
    {"word": "apprenticeship", "phrase": "formal apprenticeship program"},
    {"word": "applicant", "phrase": "job applicant screening"},
    {"word": "orientation", "phrase": "new employee orientation"},
    {"word": "tenure", "phrase": "long company tenure"},
    {"word": "successor", "phrase": "CEO's designated successor"},
    {"word": "predecessor", "phrase": "follow the predecessor's plan"},
    {"word": "prospective", "phrase": "prospective clients"},
    {"word": "novice", "phrase": "a novice in marketing"},
    {"word": "executive", "phrase": "senior executive team"},
    {"word": "personnel", "phrase": "personnel department"},
    {"word": "senior", "phrase": "senior project manager"},
    {"word": "junior", "phrase": "junior data analyst"},
    {"word": "interview", "phrase": "conduct a job interview"},
    {"word": "select", "phrase": "select top candidates"},
    {"word": "appoint", "phrase": "appoint department head"},
    {"word": "train", "phrase": "train new recruits"},
    {"word": "develop", "phrase": "develop professional skills"},
    {"word": "assess", "phrase": "assess work efficiency"},
    {"word": "evaluate", "phrase": "evaluate team performance"},
    {"word": "feedback", "phrase": "provide constructive feedback"},
    {"word": "recognition", "phrase": "gain company recognition"},
    {"word": "reward", "phrase": "reward outstanding performance"},
    {"word": "promotion", "phrase": "get a promotion"},
    {"word": "career", "phrase": "build a successful career"},
    {"word": "professional", "phrase": "professional behavior"},
    {"word": "competent", "phrase": "competent team leader"},
    {"word": "experienced", "phrase": "experienced salesperson"},
    {"word": "trainee", "phrase": "management trainee"},
    {"word": "intern", "phrase": "summer intern program"},
    {"word": "staff", "phrase": "full-time staff members"},
    {"word": "employee", "phrase": "company employee benefits"},
    {"word": "employer", "phrase": "responsible employer"},
    {"word": "recruitment", "phrase": "campus recruitment drive"},
    {"word": "selection", "phrase": "candidate selection process"},
    {"word": "placement", "phrase": "job placement service"},
    {"word": "onboarding", "phrase": "employee onboarding process"},
    {"word": "probation", "phrase": "three-month probation period"},
    {"word": "permanent", "phrase": "permanent job position"},
    {"word": "temporary", "phrase": "temporary work assignment"},
    {"word": "contract", "phrase": "sign employment contract"},
    {"word": "part-time", "phrase": "part-time work hours"},
    {"word": "full-time", "phrase": "full-time employment"},
    {"word": "resign", "phrase": "resign from the company"},
    {"word": "retire", "phrase": "retire at 65"},
    {"word": "dismiss", "phrase": "dismiss for violation"},
    {"word": "layoff", "phrase": "company layoff notice"},
    {"word": "salary", "phrase": "monthly base salary"},
    {"word": "wage", "phrase": "hourly wage rate"},
    {"word": "bonus", "phrase": "annual performance bonus"},
    {"word": "benefit", "phrase": "health insurance benefit"},

  { "word": "convention", "phrase": "attend the annual convention" },
  { "word": "meeting", "phrase": "schedule a team meeting" },
  { "word": "seminar", "phrase": "participate in a training seminar" },
  { "word": "workshop", "phrase": "conduct a hands-on workshop" },
  { "word": "forum", "phrase": "join the online discussion forum" },
  { "word": "symposium", "phrase": "present at the international symposium" },
  { "word": "lecture", "phrase": "attend a guest lecture" },
  { "word": "talk", "phrase": "give a brief talk" },
  { "word": "speech", "phrase": "deliver the keynote speech" },
  { "word": "address", "phrase": "address the audience formally" },
  { "word": "presentation", "phrase": "prepare a slide presentation" },
  { "word": "demonstration", "phrase": "watch a product demonstration" },
  { "word": "briefing", "phrase": "receive a daily briefing" },
  { "word": "debriefing", "phrase": "conduct a post-mission debriefing" },
  { "word": "discussion", "phrase": "lead a group discussion" },
  { "word": "negotiation", "phrase": "enter into salary negotiations" },
  { "word": "conference", "phrase": "host a virtual conference" },
  { "word": "session", "phrase": "attend a breakout session" },
  { "word": "agenda", "phrase": "set the meeting agenda" },
  { "word": "correspondence", "phrase": "manage email correspondence" },
  { "word": "clarify", "phrase": "clarify the project requirements" },
  { "word": "conduct", "phrase": "conduct a market survey" },
  { "word": "submit", "phrase": "submit the report by Friday" },
  { "word": "approve", "phrase": "approve the budget proposal" },
  { "word": "confirm", "phrase": "confirm your attendance" },
  { "word": "inform", "phrase": "inform all team members" },
  { "word": "inquire", "phrase": "inquire about the status" },
  { "word": "respond", "phrase": "respond to the inquiry promptly" },
  { "word": "discuss", "phrase": "discuss the new strategy" },
  { "word": "negotiate", "phrase": "negotiate better terms" },
  { "word": "propose", "phrase": "propose a solution" },
  { "word": "minutes", "phrase": "take the meeting minutes" },
  { "word": "consultation", "phrase": "seek expert consultation" },
  { "word": "advisory", "phrase": "issue a travel advisory" },
  { "word": "counsel", "phrase": "provide legal counsel" },
  { "word": "advice", "phrase": "follow professional advice" },
  { "word": "suggestion", "phrase": "make a helpful suggestion" },
  { "word": "recommendation", "phrase": "accept the committee's recommendation" },
  { "word": "proposal", "phrase": "review the business proposal" },
  { "word": "offer", "phrase": "receive a job offer" },
  { "word": "bid", "phrase": "submit a bid for the contract" },
  { "word": "quote", "phrase": "get a price quote" },
  { "word": "estimate", "phrase": "provide a cost estimate" },
  { "word": "price", "phrase": "set a competitive price" },
  { "word": "cost", "phrase": "reduce production costs" },
  { "word": "fee", "phrase": "pay the service fee" },
  { "word": "charge", "phrase": "include a delivery charge" },
  { "word": "expense", "phrase": "track business expenses" },
  { "word": "budget", "phrase": "create an annual budget" },
  { "word": "finance", "phrase": "manage corporate finance" },
  { "word": "fund", "phrase": "secure funding for the project" },
  { "word": "investment", "phrase": "make a wise investment" },
  { "word": "return", "phrase": "expect a high return" },
  { "word": "profit", "phrase": "increase company profits" },
  { "word": "loss", "phrase": "report a financial loss" },
  { "word": "revenue", "phrase": "generate more revenue" },
  { "word": "income", "phrase": "supplement your income" },
  { "word": "earning", "phrase": "boost quarterly earnings" },
  { "word": "expenditure", "phrase": "control government expenditure" },
  { "word": "outlay", "phrase": "justify the initial outlay" },
  { "word": "capital", "phrase": "raise more capital" },
  { "word": "asset", "phrase": "manage company assets" },
  { "word": "liability", "phrase": "reduce legal liabilities" },
  { "word": "equity", "phrase": "build home equity" },
  { "word": "debt", "phrase": "pay off the debt" },
  { "word": "credit", "phrase": "establish good credit" },
  { "word": "loan", "phrase": "apply for a bank loan" },
  { "word": "mortgage", "phrase": "take out a mortgage" },
  { "word": "lease", "phrase": "sign a car lease" },
  { "word": "rent", "phrase": "pay the monthly rent" },
  { "word": "payment", "phrase": "make a timely payment" },
  { "word": "receipt", "phrase": "keep the receipt for records" },
  { "word": "invoice", "phrase": "send the invoice immediately" },
  { "word": "bill", "phrase": "pay the utility bill" },
  { "word": "statement", "phrase": "review the bank statement" },
  { "word": "account", "phrase": "open a savings account" },
  { "word": "transaction", "phrase": "complete the transaction online" },
  { "word": "deal", "phrase": "close a business deal" },
  { "word": "agreement", "phrase": "reach a mutual agreement" },
  { "word": "contract", "phrase": "sign the employment contract" },
  { "word": "pact", "phrase": "form a trade pact" },
  { "word": "treaty", "phrase": "ratify the peace treaty" },
  { "word": "compact", "phrase": "enter into a compact" },
  { "word": "understanding", "phrase": "have a clear understanding" },
  { "word": "arrangement", "phrase": "make travel arrangements" },
  { "word": "commitment", "phrase": "honor your commitment" },
  { "word": "obligation", "phrase": "fulfill legal obligations" },
  { "word": "responsibility", "phrase": "take on more responsibility" },
  { "word": "duty", "phrase": "perform your duties diligently" },
  { "word": "accountability", "phrase": "ensure public accountability" },
  { "word": "guarantee", "phrase": "offer a money-back guarantee" },
  { "word": "warranty", "phrase": "extend the product warranty" },
  { "word": "insurance", "phrase": "purchase health insurance" },
  { "word": "assurance", "phrase": "provide quality assurance" },
  { "word": "security", "phrase": "enhance network security" },
  { "word": "safety", "phrase": "prioritize workplace safety" },
  { "word": "protection", "phrase": "seek legal protection" },
  { "word": "program", "phrase": "launch a new program" },
  { "word": "project", "phrase": "manage the construction project" },
  { "word": "campaign", "phrase": "run a marketing campaign" },
  { "word": "effort", "phrase": "make a concerted effort" },
  { "word": "endeavor", "phrase": "support this noble endeavor" },
  { "word": "attempt", "phrase": "make another attempt" },
  { "word": "try", "phrase": "try a different approach" },
  { "word": "experiment", "phrase": "conduct an experiment" },
  { "word": "venture", "phrase": "start a new venture" },
  { "word": "undertaking", "phrase": "begin a major undertaking" },
  { "word": "enterprise", "phrase": "grow the family enterprise" },
  { "word": "activity", "phrase": "plan outdoor activities" },
  { "word": "action", "phrase": "take immediate action" },
  { "word": "operation", "phrase": "oversee daily operations" },
  { "word": "function", "phrase": "perform its intended function" },
  { "word": "safeguard", "phrase": "implement safeguards" },
  { "word": "precaution", "phrase": "take necessary precautions" },
  { "word": "measure", "phrase": "adopt safety measures" },
  { "word": "step", "phrase": "follow each step carefully" },
  { "word": "initiative", "phrase": "take the initiative" },
  { "word": "plan", "phrase": "develop a strategic plan" },
  { "word": "strategy", "phrase": "formulate a new strategy" },
  { "word": "tactic", "phrase": "use aggressive tactics" },
  { "word": "method", "phrase": "apply scientific methods" },
  { "word": "approach", "phrase": "adopt a holistic approach" },
  { "word": "way", "phrase": "find a better way" },
  { "word": "means", "phrase": "by all means necessary" },
  { "word": "technique", "phrase": "master the technique" },
  { "word": "procedure", "phrase": "follow the standard procedure" },
  { "word": "process", "phrase": "streamline the process" },
  { "word": "system", "phrase": "upgrade the computer system" },
  { "word": "scheme", "phrase": "participate in the scheme" },

  { "word": "contract", "phrase": "sign a binding contract" },
  { "word": "transaction", "phrase": "process the financial transaction" },
  { "word": "agreement", "phrase": "reach a verbal agreement" },
  { "word": "lease", "phrase": "terminate the office lease" },
  { "word": "rent", "phrase": "rent commercial space" },
  { "word": "purchase", "phrase": "approve the purchase" },
  { "word": "sale", "phrase": "announce the company sale" },
  { "word": "invoice", "phrase": "issue a proforma invoice" },
  { "word": "receipt", "phrase": "request a detailed receipt" },
  { "word": "guarantee", "phrase": "provide a satisfaction guarantee" },
  { "word": "warranty", "phrase": "honor the manufacturer's warranty" },
  { "word": "terms", "phrase": "agree to the payment terms" },
  { "word": "obligation", "phrase": "meet contractual obligations" },
  { "word": "compensate", "phrase": "compensate for the delay" },
  { "word": "compensation", "phrase": "receive fair compensation" },
  { "word": "deposit", "phrase": "make a security deposit" },
  { "word": "payment", "phrase": "delay the payment" },
  { "word": "bid", "phrase": "win the competitive bid" },
  { "word": "award", "phrase": "award the contract" },
  { "word": "price", "phrase": "match the competitor's price" },
  { "word": "cost", "phrase": "cover the additional cost" },
  { "word": "fee", "phrase": "waive the application fee" },
  { "word": "charge", "phrase": "impose a handling charge" },
  { "word": "expense", "phrase": "reimburse travel expenses" },
  { "word": "budget", "phrase": "exceed the annual budget" },
  { "word": "finance", "phrase": "finance the expansion" },
  { "word": "fund", "phrase": "allocate the research fund" },
  { "word": "investment", "phrase": "attract foreign investment" },
  { "word": "return", "phrase": "generate a steady return" },
  { "word": "profit", "phrase": "share the net profit" },
  { "word": "loss", "phrase": "suffer a heavy loss" },
  { "word": "revenue", "phrase": "report quarterly revenue" },
  { "word": "income", "phrase": "diversify income streams" },
  { "word": "earning", "phrase": "boost its earnings" },
  { "word": "expenditure", "phrase": "cut public expenditure" },
  { "word": "outlay", "phrase": "justify the capital outlay" },
  { "word": "capital", "phrase": "access venture capital" },
  { "word": "asset", "phrase": "liquidate the asset" },
  { "word": "liability", "phrase": "assume full liability" },
  { "word": "equity", "phrase": "offer equity to employees" },
  { "word": "debt", "phrase": "service its debt" },
  { "word": "credit", "phrase": "extend a line of credit" },
  { "word": "loan", "phrase": "repay the business loan" },
  { "word": "mortgage", "phrase": "refinance the mortgage" },
  { "word": "bill", "phrase": "dispute the telephone bill" },
  { "word": "statement", "phrase": "reconcile the monthly statement" },
  { "word": "account", "phrase": "settle the outstanding account" },
  { "word": "deal", "phrase": "broker a major deal" },
  { "word": "pact", "phrase": "form a strategic pact" },
  { "word": "treaty", "phrase": "violate the international treaty" },
  { "word": "compact", "phrase": "enter a binding compact" },
  { "word": "understanding", "phrase": "reach a mutual understanding" },
  { "word": "arrangement", "phrase": "finalize the seating arrangement" },
  { "word": "commitment", "phrase": "demonstrate a strong commitment" },
  { "word": "responsibility", "phrase": "delegate the responsibility" },
  { "word": "duty", "phrase": "neglect his duty" },
  { "word": "accountability", "phrase": "demand greater accountability" },
  { "word": "insurance", "phrase": "file an insurance claim" },
  { "word": "assurance", "phrase": "give his personal assurance" },
  { "word": "security", "phrase": "breach data security" },
  { "word": "safety", "phrase": "compromise public safety" },
  { "word": "protection", "phrase": "seek environmental protection" },
  { "word": "safeguard", "phrase": "act as a safeguard" },
  { "word": "precaution", "phrase": "take standard precautions" },
  { "word": "measure", "phrase": "implement austerity measures" },
  { "word": "step", "phrase": "take corrective steps" },
  { "word": "action", "phrase": "demand swift action" },
  { "word": "initiative", "phrase": "support the green initiative" },
  { "word": "plan", "phrase": "execute the contingency plan" },
  { "word": "strategy", "phrase": "devise an exit strategy" },
  { "word": "tactic", "phrase": "change their negotiation tactics" },
  { "word": "method", "phrase": "employ unconventional methods" },
  { "word": "approach", "phrase": "adopt a flexible approach" },
  { "word": "way", "phrase": "pave the way" },
  { "word": "means", "phrase": "by any means possible" },
  { "word": "technique", "phrase": "apply modern techniques" },
  { "word": "procedure", "phrase": "simplify the application procedure" },
  { "word": "process", "phrase": "automate the entire process" },
  { "word": "system", "phrase": "integrate the new system" },
  { "word": "scheme", "phrase": "launch a pension scheme" },
  { "word": "program", "phrase": "enroll in the loyalty program" },
  { "word": "project", "phrase": "complete the pilot project" },
  { "word": "campaign", "phrase": "fund the advertising campaign" },
  { "word": "effort", "phrase": "redouble their efforts" },
  { "word": "endeavor", "phrase": "a joint scientific endeavor" },
  { "word": "attempt", "phrase": "a final attempt" },
  { "word": "try", "phrase": "try a different method" },
  { "word": "experiment", "phrase": "a social experiment" },
  { "word": "venture", "phrase": "a risky joint venture" },
  { "word": "undertaking", "phrase": "a massive undertaking" },
  { "word": "enterprise", "phrase": "a state-owned enterprise" },
  { "word": "activity", "phrase": "suspend all activities" },
  { "word": "operation", "phrase": "resume normal operations" },
  { "word": "function", "phrase": "serve a vital function" },
  { "word": "merchandise", "phrase": "display the new merchandise" },
  { "word": "promotion", "phrase": "launch a sales promotion" },
  { "word": "advertise", "phrase": "advertise on social media" },
  { "word": "campaign", "phrase": "a successful marketing campaign" },
  { "word": "brochure", "phrase": "download the product brochure" },
  { "word": "brand", "phrase": "build a strong brand" },
  { "word": "customer", "phrase": "retain loyal customers" },
  { "word": "consumer", "phrase": "protect consumer rights" },
  { "word": "want", "phrase": "identify customer wants" },
  { "word": "desire", "phrase": "create a desire" },
  { "word": "preference", "phrase": "state your preference" },
  { "word": "choice", "phrase": "offer more choice" },
  { "word": "option", "phrase": "consider all options" },
  { "word": "alternative", "phrase": "find an alternative" },
  { "word": "selection", "phrase": "a wide selection" },
  { "word": "variety", "phrase": "for a variety of reasons" },
  { "word": "range", "phrase": "a full range of services" },
  { "word": "line", "phrase": "a new product line" },
  { "word": "collection", "phrase": "a seasonal collection" },
  { "word": "series", "phrase": "a lecture series" },
  { "word": "trademark", "phrase": "register a trademark" },
  { "word": "logo", "phrase": "design a new logo" },
  { "word": "label", "phrase": "read the label carefully" },
  { "word": "packaging", "phrase": "eco-friendly packaging" },
  { "word": "package", "phrase": "a complete software package" },
  { "word": "container", "phrase": "a shipping container" },
  { "word": "design", "phrase": "faulty by design" },
  { "word": "style", "phrase": "in a formal style" },
  { "word": "model", "phrase": "the latest model" },
  { "word": "type", "phrase": "a new type of" },
  { "word": "kind", "phrase": "all kinds of" },
  { "word": "sort", "phrase": "this sort of thing" },
  { "word": "category", "phrase": "fall into this category" },
  { "word": "classification", "phrase": "security classification" },
  { "word": "group", "phrase": "target a specific group" },
  { "word": "segment", "phrase": "the youth segment" },
  { "word": "target", "phrase": "meet the target" },
  { "word": "audience", "phrase": "target your audience" },
  { "word": "demographic", "phrase": "key demographics" },
  { "word": "psychographic", "phrase": "psychographic profiling" },
  { "word": "geographic", "phrase": "geographic expansion" },
  { "word": "behavioral", "phrase": "behavioral data" },
  { "word": "marketing", "phrase": "direct marketing" },
  { "word": "advertising", "phrase": "false advertising" },
  { "word": "publicity", "phrase": "generate positive publicity" },
  { "word": "public relations", "phrase": "a public relations crisis" },
  { "word": "sales", "phrase": "boost sales figures" },
  { "word": "distribution", "phrase": "global distribution network" },
  { "word": "logistics", "phrase": "manage the logistics" },
  { "word": "supply chain", "phrase": "a resilient supply chain" },
  { "word": "inventory", "phrase": "reduce excess inventory" },
  { "word": "stock", "phrase": "out of stock" },
  { "word": "warehouse", "phrase": "a central warehouse" },
  { "word": "storage", "phrase": "cloud storage" },
  { "word": "transportation", "phrase": "public transportation" },
  { "word": "shipping", "phrase": "free shipping" },
  { "word": "delivery", "phrase": "next-day delivery" },
  { "word": "fulfillment", "phrase": "order fulfillment center" },
  { "word": "customer service", "phrase": "excellent customer service" },
  { "word": "support", "phrase": "technical support" },
  { "word": "after-sales", "phrase": "after-sales support" },
  { "word": "warranty", "phrase": "a one-year warranty" },
  { "word": "guarantee", "phrase": "a money-back guarantee" },
  { "word": "scheme", "phrase": "a pension scheme" },
  { "word": "program", "phrase": "a training program" },
  { "word": "project", "phrase": "a construction project" },
  { "word": "effort", "phrase": "a joint effort" },
  { "word": "endeavor", "phrase": "a business endeavor" },
  { "word": "attempt", "phrase": "a failed attempt" },
  { "word": "try", "phrase": "give it a try" },
  { "word": "experiment", "phrase": "a scientific experiment" },
  { "word": "venture", "phrase": "a new venture" },
  { "word": "undertaking", "phrase": "a major undertaking" },
  { "word": "enterprise", "phrase": "a private enterprise" },
  { "word": "activity", "phrase": "core business activity" },
  { "word": "action", "phrase": "take legal action" },
  { "word": "operation", "phrase": "smooth operation" },
  { "word": "function", "phrase": "perform a vital function" },
  { "word": "term", "phrase": "long-term growth" },
  { "word": "duration", "phrase": "for the duration of" },
  { "word": "length", "phrase": "at great length" },
  { "word": "time", "phrase": "ahead of time" },
  { "word": "date", "phrase": "to date" },
  { "word": "deadline", "phrase": "meet the deadline" },
  { "word": "schedule", "phrase": "ahead of schedule" },
  { "word": "timeline", "phrase": "a realistic timeline" },
  { "word": "timetable", "phrase": "a strict timetable" },
  { "word": "plan", "phrase": "a strategic plan" },
  { "word": "arrangement", "phrase": "make special arrangements" },
  { "word": "organization", "phrase": "non-profit organization" },
  { "word": "coordination", "phrase": "require close coordination" },
  { "word": "management", "phrase": "middle management" },
  { "word": "administration", "phrase": "day-to-day administration" },
  { "word": "supervision", "phrase": "under the supervision of" },
  { "word": "control", "phrase": "budgetary control" },
  { "word": "direction", "phrase": "under his direction" },
  { "word": "return", "phrase": "a high return" },
  { "word": "refund", "phrase": "demand a full refund" },
  { "word": "exchange", "phrase": "a foreign exchange" },
  { "word": "complaint", "phrase": "file a formal complaint" },
  { "word": "feedback", "phrase": "constructive feedback" },
  { "word": "review", "phrase": "annual performance review" },
  { "word": "rating", "phrase": "a five-star rating" },
  { "word": "recommendation", "phrase": "a strong recommendation" },
  { "word": "referral", "phrase": "a customer referral" },
  { "word": "loyalty", "phrase": "customer loyalty" },
  { "word": "trust", "phrase": "breach of trust" },
  { "word": "relationship", "phrase": "a professional relationship" },
  { "word": "connection", "phrase": "a personal connection" },
  { "word": "network", "phrase": "a professional network" },
  { "word": "partnership", "phrase": "enter into a partnership" },
  { "word": "collaboration", "phrase": "close collaboration" },
  { "word": "cooperation", "phrase": "international cooperation" },
  { "word": "alliance", "phrase": "form a strategic alliance" },
  { "word": "joint venture", "phrase": "establish a joint venture" },
  { "word": "affiliation", "phrase": "corporate affiliation" },
  { "word": "association", "phrase": "professional association" },
  { "word": "membership", "phrase": "renew your membership" },
  { "word": "subscription", "phrase": "cancel your subscription" },
  { "word": "renewal", "phrase": "automatic renewal" },
  { "word": "cancellation", "phrase": "a last-minute cancellation" },
  { "word": "termination", "phrase": "contract termination" },
  { "word": "expiration", "phrase": "upon expiration" },
  { "word": "validity", "phrase": "check its validity" },
  { "word": "period", "phrase": "a trial period" },
  { "word": "counterfeit", "phrase": "counterfeit products" },
  { "word": "fake", "phrase": "a fake review" },
  { "word": "false", "phrase": "a false statement" },
  { "word": "spurious", "phrase": "spurious claims" },
  { "word": "bogus", "phrase": "a bogus company" },
  { "word": "fraudulent", "phrase": "fraudulent activity" },
  { "word": "deceptive", "phrase": "deceptive advertising" },
  { "word": "misleading", "phrase": "misleading information" },
  { "word": "dishonest", "phrase": "dishonest practices" },
  { "word": "unethical", "phrase": "unethical behavior" },
  { "word": "illegal", "phrase": "illegal activity" },
  { "word": "lawful", "phrase": "a lawful purpose" },
  { "word": "legal", "phrase": "seek legal advice" },
  { "word": "legitimate", "phrase": "a legitimate concern" },
  { "word": "valid", "phrase": "a valid reason" },
  { "word": "invalid", "phrase": "an invalid argument" },
  { "word": "void", "phrase": "null and void" },
  { "word": "null", "phrase": "declare it null" },
  { "word": "binding", "phrase": "a binding agreement" },
  { "word": "leadership", "phrase": "demonstrate strong leadership" },
  { "word": "guidance", "phrase": "provide clear guidance" },
  { "word": "assistance", "phrase": "offer assistance" },
  { "word": "help", "phrase": "a great help" },
  { "word": "aid", "phrase": "foreign aid" },
  { "word": "facility", "phrase": "research facility" },
  { "word": "resource", "phrase": "allocate resources" },
  { "word": "tool", "phrase": "a useful tool" },
  { "word": "equipment", "phrase": "safety equipment" },
  { "word": "machinery", "phrase": "heavy machinery" },
  { "word": "technology", "phrase": "emerging technology" },
  { "word": "system", "phrase": "operating system" },
  { "word": "software", "phrase": "proprietary software" },
  { "word": "hardware", "phrase": "computer hardware" },
  { "word": "application", "phrase": "a practical application" },
  { "word": "platform", "phrase": "a digital platform" },
  { "word": "internet", "phrase": "high-speed internet" },
  { "word": "website", "phrase": "visit our website" },
  { "word": "app", "phrase": "mobile app" },
  { "word": "mobile", "phrase": "mobile technology" },
  { "word": "digital", "phrase": "digital transformation" },
  { "word": "online", "phrase": "shop online" },
  { "word": "offline", "phrase": "offline mode" },
  { "word": "virtual", "phrase": "a virtual meeting" },
  { "word": "physical", "phrase": "physical presence" },
  { "word": "real", "phrase": "in real time" },
  { "word": "actual", "phrase": "actual cost" },
  { "word": "genuine", "phrase": "genuine interest" },
  { "word": "authentic", "phrase": "authentic product" },
  { "word": "original", "phrase": "original idea" },
  { "word": "copy", "phrase": "a hard copy" },
  { "word": "duplicate", "phrase": "a duplicate copy" },
  { "word": "replica", "phrase": "a replica" },
  { "word": "laws", "phrase": "obey the laws" },
  { "word": "policies", "phrase": "company policies" },
  { "word": "procedures", "phrase": "standard procedures" },
  { "word": "protocols", "phrase": "safety protocols" },
  { "word": "guidelines", "phrase": "follow the guidelines" },
  { "word": "instructions", "phrase": "written instructions" },
  { "word": "directions", "phrase": "clear directions" },
  { "word": "orders", "phrase": "follow orders" },
  { "word": "commands", "phrase": "issue commands" },
  { "word": "requests", "phrase": "reasonable requests" },
  { "word": "demands", "phrase": "unreasonable demands" },
  { "word": "requirements", "phrase": "meet the requirements" },
  { "word": "needs", "phrase": "customer needs" },
  { "word": "wants", "phrase": "consumer wants" },
  { "word": "desires", "phrase": "fulfill desires" },
  { "word": "expectations", "phrase": "exceed expectations" },
  { "word": "hopes", "phrase": "raise hopes" },
  { "word": "wishes", "phrase": "best wishes" },
  { "word": "enforceable", "phrase": "legally enforceable" },
  { "word": "unenforceable", "phrase": "an unenforceable clause" },
  { "word": "liable", "phrase": "held liable" },
  { "word": "accountable", "phrase": "hold accountable" },
  { "word": "responsible", "phrase": "responsible for" },
  { "word": "obligated", "phrase": "feel obligated" },
  { "word": "committed", "phrase": "deeply committed" },
  { "word": "dedicated", "phrase": "dedicated to" },
  { "word": "devoted", "phrase": "devoted customer" },
  { "word": "faithful", "phrase": "remain faithful" },
  { "word": "trustworthy", "phrase": "a trustworthy partner" },
  { "word": "reliable", "phrase": "a reliable source" },
  { "word": "dependable", "phrase": "dependable service" },
  { "word": "credible", "phrase": "a credible threat" },
  { "word": "believable", "phrase": "hardly believable" },
  { "word": "honest", "phrase": "honest mistake" },
  { "word": "ethical", "phrase": "ethical standards" },
  { "word": "moral", "phrase": "a moral obligation" },
  { "word": "upright", "phrase": "an upright citizen" },
  { "word": "principled", "phrase": "a principled stand" },
  { "word": "integrity", "phrase": "professional integrity" },
  { "word": "honesty", "phrase": "honesty is the best policy" },
  { "word": "ethics", "phrase": "business ethics" },
  { "word": "morality", "phrase": "public morality" },
  { "word": "values", "phrase": "core values" },
  { "word": "standards", "phrase": "high standards" },
  { "word": "principles", "phrase": "guiding principles" },
  { "word": "rules", "phrase": "follow the rules" },
  { "word": "regulations", "phrase": "government regulations" },
    { "word": "revenue", "phrase": "Annual revenue exceeded expectations." },
    { "word": "profit", "phrase": "Net profit margins are shrinking." },
    { "word": "expense", "phrase": "Submit your travel expense report." },
    { "word": "budget", "phrase": "The project is over budget." },
    { "word": "invoice", "phrase": "Process the invoice for payment." },
    { "word": "receipt", "phrase": "Please keep your receipt." },
    { "word": "account", "phrase": "Reconcile the bank account monthly." },
    { "word": "payment", "phrase": "Your payment is now overdue." },
    { "word": "deposit", "phrase": "A security deposit is required." },
    { "word": "refund", "phrase": "We processed your refund request." },
    { "word": "tax", "phrase": "File your corporate tax return." },
    { "word": "fee", "phrase": "There is a service fee." },
    { "word": "charge", "phrase": "A late charge will apply." },
    { "word": "cost", "phrase": "We must reduce operating costs." },
    { "word": "capital", "phrase": "We need to raise more capital." },
    { "word": "asset", "phrase": "Our greatest asset is our staff." },
    { "word": "liability", "phrase": "It's a potential legal liability." },
    { "word": "equity", "phrase": "He has equity in the company." },
    { "word": "debt", "phrase": "The company is in debt." },
    { "word": "credit", "phrase": "Your credit limit has been increased." },
    { "word": "loan", "phrase": "We applied for a business loan." },
    { "word": "mortgage", "phrase": "They took out a large mortgage." },
    { "word": "salary", "phrase": "Her salary is paid monthly." },
    { "word": "wage", "phrase": "The minimum wage increased this year." },
    { "word": "bonus", "phrase": "Employees received a performance bonus." },
    { "word": "commission", "phrase": "She works on a commission basis." },
    { "word": "allowance", "phrase": "You have a daily meal allowance." },
    { "word": "raise", "phrase": "He asked for a pay raise." },
    { "word": "financial", "phrase": "Review the financial statements carefully." },
    { "word": "accountant", "phrase": "Consult with your accountant first." },
    { "word": "auditor", "phrase": "The external auditor will visit next week." },
    { "word": "bookkeeping", "phrase": "Accurate bookkeeping is essential." },
    { "word": "record", "phrase": "Keep a record of all transactions." },
  { "word": "stationery", "phrase": "Order more office stationery." },
  { "word": "enclose", "phrase": "Please enclose a self-addressed envelope." },
  { "word": "submit", "phrase": "Submit your application online." },
  { "word": "approve", "phrase": "The manager must approve this." },
  { "word": "arrange", "phrase": "Arrange a meeting for next week." },
  { "word": "register", "phrase": "Register for the conference early." },
  { "word": "reserve", "phrase": "I'd like to reserve a seat." },
  { "word": "policy", "phrase": "It's against company policy." },
  { "word": "instruction", "phrase": "Follow the instructions carefully." },
  { "word": "memo", "phrase": "Did you read the internal memo?" },
  { "word": "letter", "phrase": "A formal letter of complaint" },
  { "word": "email", "phrase": "Send me an email confirmation." },
  { "word": "report", "phrase": "The annual sales report" },
  { "word": "document", "phrase": "Please sign this document." },
  { "word": "file", "phrase": "Save the file on the server." },
  { "word": "form", "phrase": "Fill out this application form." },
  { "word": "application", "phrase": "Your application is under review." },
  { "word": "registration", "phrase": "The registration fee is $50." },
  { "word": "confirmation", "phrase": "I haven't received a confirmation." },
  { "word": "notification", "phrase": "You will receive a notification." },
  { "word": "announcement", "phrase": "An important announcement is coming." },
  { "word": "notice", "phrase": "We received an eviction notice." },
  { "word": "alert", "phrase": "A security alert was issued." },
  { "word": "warning", "phrase": "Read the warning label first." },
  { "word": "message", "phrase": "Leave a message after the tone." },
  { "word": "communication", "phrase": "Effective communication is key." },
  { "word": "mail", "phrase": "The check is in the mail." },
  { "word": "post", "phrase": "I will post the letter today." },
  { "word": "courier", "phrase": "Send the package by courier." },
  { "word": "express", "phrase": "We offer express delivery." },
  { "word": "delivery", "phrase": "Track your delivery online." },
  { "word": "pickup", "phrase": "Schedule a pickup time." },
  { "word": "dropoff", "phrase": "Designated dropoff location" },
  { "word": "office", "phrase": "The head office is in London." },
  { "word": "desk", "phrase": "I left it on your desk." },
  { "word": "chair", "phrase": "An ergonomic office chair" },
  { "word": "table", "phrase": "Please refer to Table 2." },
  { "word": "computer", "phrase": "My computer crashed again." },
  { "word": "laptop", "phrase": "A new company laptop" },
  { "word": "printer", "phrase": "The printer is out of ink." },
  { "word": "scanner", "phrase": "Use the document scanner." },
  { "word": "copier", "phrase": "The copier is jammed." },
  { "word": "fax", "phrase": "Please fax the signed contract." },
  { "word": "phone", "phrase": "The phone is for you." },
  { "word": "telephone", "phrase": "A telephone conference call" },
  { "word": "cellphone", "phrase": "No cellphone use during meetings." },
  { "word": "hardware", "phrase": "Computer hardware and software" },
  { "word": "platform", "phrase": "Our new online platform" },
  { "word": "network", "phrase": "The corporate network is down." },
  { "word": "device", "phrase": "A mobile electronic device" },
  { "word": "appliance", "phrase": "A common household appliance" },
  { "word": "gadget", "phrase": "The latest tech gadget" },
  { "word": "instrument", "phrase": "A precision measuring instrument" },
  { "word": "implement", "phrase": "Implement the new policy." },
  { "word": "utensil", "phrase": "Kitchen utensils and supplies" },
  { "word": "supplies", "phrase": "Running low on office supplies" },
  { "word": "paper", "phrase": "Print it on recycled paper." },
  { "word": "pen", "phrase": "Do you have a pen?" },
  { "word": "pencil", "phrase": "Write in pencil, not pen." },
  { "word": "marker", "phrase": "Use a permanent marker." },
  { "word": "highlighter", "phrase": "Highlight the key points." },
  { "word": "eraser", "phrase": "I need an eraser." },
  { "word": "sharpener", "phrase": "A pencil sharpener" },
  { "word": "ruler", "phrase": "Use a ruler to draw lines." },
  { "word": "scissors", "phrase": "A pair of scissors" },
  { "word": "stapler", "phrase": "The stapler is empty." },
  { "word": "staples", "phrase": "We're out of staples." },
  { "word": "paperclip", "phrase": "Attach the pages with a paperclip." },
  { "word": "clip", "phrase": "A clip for your documents" },
  { "word": "folder", "phrase": "Create a new project folder." },
  { "word": "binder", "phrase": "A three-ring binder" },
  { "word": "notebook", "phrase": "Take notes in your notebook." },
  { "word": "journal", "phrase": "A professional trade journal" },
  { "word": "diary", "phrase": "Keep a work diary." },
  { "word": "calendar", "phrase": "Check the team calendar." },
  { "word": "planner", "phrase": "My daily planner is full." },
  { "word": "schedule", "phrase": "My schedule is very tight." },
  { "word": "timeline", "phrase": "We are behind the timeline." },
  { "word": "timetable", "phrase": "The bus timetable changed." },
  { "word": "environment", "phrase": "A positive work environment" },
  { "word": "workplace", "phrase": "Safety in the workplace" },
  { "word": "building", "phrase": "The main building is closed." },
  { "word": "room", "phrase": "Is the conference room available?" },
  { "word": "space", "phrase": "We need more storage space." },
  { "word": "area", "phrase": "This is a no-smoking area." },
  { "word": "location", "phrase": "The exact location is unknown." },
  { "word": "address", "phrase": "Please update your address." },
  { "word": "contact", "phrase": "Our main contact person" },
  { "word": "information", "phrase": "For more information, visit our website." },
  { "word": "data", "phrase": "We analyzed the sales data." },
  { "word": "fact", "phrase": "In fact, the opposite is true." },
  { "word": "figure", "phrase": "Please see Figure 1." },
  { "word": "statistic", "phrase": "A surprising statistic" },
  { "word": "detail", "phrase": "Pay attention to every detail." },
  { "word": "particular", "phrase": "No one in particular" },
  { "word": "specific", "phrase": "Be more specific." },
  { "word": "general", "phrase": "In general, we are satisfied." },
  { "word": "overall", "phrase": "The overall performance was good." },
  { "word": "total", "phrase": "The total cost is $1,000." },
  { "word": "complete", "phrase": "The project is now complete." },
  { "word": "entire", "phrase": "The entire team worked hard." },
  { "word": "whole", "phrase": "The whole process took a week." },
  { "word": "full", "phrase": "We are at full capacity." },
  { "word": "partial", "phrase": "A partial refund was issued." },
  { "word": "part", "phrase": "Part of the job" },
  { "word": "piece", "phrase": "A piece of equipment" },
  { "word": "section", "phrase": "See the previous section." },
  { "word": "segment", "phrase": "Our target market segment" },
  { "word": "portion", "phrase": "A large portion of the budget" },
  { "word": "share", "phrase": "My share of the work" },
  { "word": "percentage", "phrase": "A high percentage of users" },
  { "word": "ratio", "phrase": "The student-to-teacher ratio" },
  { "word": "rate", "phrase": "The exchange rate is favorable." },
  { "word": "amount", "phrase": "A significant amount of money" },
  { "word": "quantity", "phrase": "We have a large quantity in stock." },
  { "word": "number", "phrase": "A growing number of people" },
  { "word": "count", "phrase": "The final count is in." },
  { "word": "sum", "phrase": "A large sum of money" },
  { "word": "aggregate", "phrase": "Look at the aggregate data." },
  { "word": "average", "phrase": "The average response time" },
  { "word": "mean", "phrase": "The mean score was 75." },
  { "word": "median", "phrase": "The median household income" },
  { "word": "mode", "phrase": "The mode of transport" },
  { "word": "range", "phrase": "A wide range of products" },
  { "word": "minimum", "phrase": "Meet the minimum requirements." },
  { "word": "maximum", "phrase": "The maximum capacity is 100." },
  { "word": "high", "phrase": "A high level of quality" },
  { "word": "low", "phrase": "A low chance of success" },
  { "word": "top", "phrase": "Our top priority" },
  { "word": "bottom", "phrase": "At the bottom of the page" },
  { "word": "first", "phrase": "First come, first served." },
  { "word": "last", "phrase": "Last but not least" },
  { "word": "middle", "phrase": "The middle of next month" },
  { "word": "center", "phrase": "The city center" },
  { "word": "front", "phrase": "The front desk" },
  { "word": "back", "phrase": "In the back of the room" },
  { "word": "left", "phrase": "Turn left at the corner." },
  { "word": "right", "phrase": "All rights reserved." },
  { "word": "upper", "phrase": "The upper management" },
  { "word": "lower", "phrase": "Lower your voice, please." },
  { "word": "inner", "phrase": "Inner peace" },
  { "word": "outer", "phrase": "The outer packaging was damaged." },
  { "word": "near", "phrase": "Is there a bank near here?" },
  { "word": "far", "phrase": "As far as I know" },
  { "word": "close", "phrase": "The store is close by." },
  { "word": "distant", "phrase": "A distant memory" },
  { "word": "early", "phrase": "An early start tomorrow" },
  { "word": "late", "phrase": "Better late than never." },
  { "word": "on-time", "phrase": "The train arrived on-time." },
  { "word": "punctual", "phrase": "Please be punctual." },
  { "word": "prompt", "phrase": "Thank you for your prompt reply." },
  { "word": "slow", "phrase": "A slow internet connection" },
  { "word": "fast", "phrase": "Fast food restaurant" },
  { "word": "quick", "phrase": "A quick response" },
  { "word": "rapid", "phrase": "Rapid growth" },
  { "word": "speedy", "phrase": "Wishing you a speedy recovery." },
  { "word": "unsuccessful", "phrase": "An unsuccessful attempt" },
  { "word": "failed", "phrase": "The failed product launch" },
  { "word": "achieved", "phrase": "We achieved our goal." },
  { "word": "abolished", "phrase": "The old policy was abolished." },
  { "word": "discontinued", "phrase": "The service has been discontinued." },
  { "word": "stopped", "phrase": "Production stopped last week." },
  { "word": "halted", "phrase": "All shipments have been halted." },
  { "word": "ceased", "phrase": "The company ceased operations." },
  { "word": "paused", "phrase": "The project is temporarily paused." },
  { "word": "suspended", "phrase": "His account was suspended." },
  { "word": "resumed", "phrase": "Normal service has resumed." },
  { "word": "continued", "phrase": "The meeting continued for hours." },
  { "word": "proceeded", "phrase": "We proceeded with the plan." },
  { "word": "advanced", "phrase": "Technology has advanced rapidly." },
  { "word": "progressed", "phrase": "Work has progressed well." },
  { "word": "moved forward", "phrase": "The project moved forward." },
  { "word": "developed", "phrase": "A newly developed area" },
  { "word": "evolved", "phrase": "Our strategy has evolved." },
  { "word": "changed", "phrase": "The schedule has changed." },
  { "word": "transformed", "phrase": "The industry was transformed." },
  { "word": "modified", "phrase": "The design was modified." },
  { "word": "adjusted", "phrase": "Adjusted for inflation" },
  { "word": "adapted", "phrase": "We adapted to the change." },
  { "word": "revised", "phrase": "The revised edition" },
  { "word": "updated", "phrase": "The software was updated." },
  { "word": "renewed", "phrase": "My contract was renewed." },
  { "word": "restored", "phrase": "Power was restored quickly." },
  { "word": "recovered", "phrase": "The market recovered slowly." },
  { "word": "healed", "phrase": "The injury has healed." },
  { "word": "fixed", "phrase": "The problem is fixed." },
  { "word": "repaired", "phrase": "The machine was repaired." },
  { "word": "mended", "phrase": "Their relationship was mended." },
  { "word": "corrected", "phrase": "The error was corrected." },
  { "word": "improved", "phrase": "Sales have improved significantly." },
  { "word": "enhanced", "phrase": "Enhanced security features" },
  { "word": "better", "phrase": "A better solution" },
  { "word": "worse", "phrase": "The situation got worse." },
  { "word": "same", "phrase": "More of the same" },
  { "word": "different", "phrase": "A completely different approach" },
  { "word": "similar", "phrase": "A similar problem" },
  { "word": "alike", "phrase": "They look very much alike." },
  { "word": "dissimilar", "phrase": "Two dissimilar concepts" },
  { "word": "distinct", "phrase": "A distinct advantage" },
  { "word": "unique", "phrase": "A unique selling point" },
  { "word": "special", "phrase": "Nothing special" },
  { "word": "common", "phrase": "A common mistake" },
  { "word": "ordinary", "phrase": "An ordinary day" },
  { "word": "usual", "phrase": "As usual" },
  { "word": "normal", "phrase": "Under normal circumstances" },
  { "word": "regular", "phrase": "A regular customer" },
  { "word": "standard", "phrase": "The industry standard" },
  { "word": "typical", "phrase": "A typical example" },
  
    { "word": "beverage", "phrase": "Complementary beverage service is provided." },
    { "word": "bid", "phrase": "The winning bid was announced." },
    { "word": "billion", "phrase": "Sales exceeded five billion dollars." },
    { "word": "biography", "phrase": "Read the founder's biography." },
    { "word": "bistro", "phrase": "Let's meet at the new bistro." },
    { "word": "booking", "phrase": "I need to confirm my booking." },
    { "word": "booth", "phrase": "Visit our booth at the fair." },
    { "word": "boulevard", "phrase": "The office is on Main Boulevard." },
    { "word": "branch", "phrase": "Our downtown branch is closed." },
    { "word": "brick", "phrase": "A brick-and-mortar store" },
    { "word": "access", "phrase": "You need an access card." },
    { "word": "accommodate", "phrase": "We can accommodate your request." },
    { "word": "accompany", "phrase": "Will you accompany the client?" },
    { "word": "acknowledge", "phrase": "Please acknowledge receipt of this." },
    { "word": "acquire", "phrase": "The company will acquire a competitor." },
    { "word": "act", "phrase": "We must act quickly." },
    { "word": "affect", "phrase": "This will affect our timeline." },
    { "word": "afford", "phrase": "We cannot afford any delays." },
    { "word": "acceptance", "phrase": "Thank you for your acceptance." },
    { "word": "accessory", "phrase": "A necessary computer accessory" },
    { "word": "accomplishment", "phrase": "A major accomplishment" },
    { "word": "account", "phrase": "Please settle your account." },
    { "word": "achievement", "phrase": "A remarkable achievement" },
    { "word": "acquisition", "phrase": "The latest company acquisition" },
    { "word": "admission", "phrase": "Admission to the museum is free." },
    { "word": "advertisement", "phrase": "Place an advertisement in the paper." },
    { "word": "advisor", "phrase": "Schedule a meeting with your advisor." },
    { "word": "aerobics", "phrase": "Aerobics class is at noon." },
    { "word": "agenda", "phrase": "Let's set the agenda." },
    { "word": "agreement", "phrase": "We have a verbal agreement." },
    { "word": "agriculture", "phrase": "Modern agriculture technology" },
    { "word": "aircraft", "phrase": "A commercial aircraft" },
    { "word": "airline", "phrase": "Which airline are you flying?" },
    { "word": "amenity", "phrase": "The hotel amenity was great." },
    { "word": "analysis", "phrase": "A detailed cost analysis" },
    { "word": "apparel", "phrase": "Professional business apparel" },
    { "word": "appliance", "phrase": "A kitchen appliance" },
    { "word": "architect", "phrase": "Consult the project architect." },
    { "word": "array", "phrase": "A wide array of options" },
    { "word": "arrival", "phrase": "Estimated time of arrival" },
    { "word": "artwork", "phrase": "Office artwork" },
    { "word": "aspect", "phrase": "Consider every aspect carefully." },
    { "word": "assignment", "phrase": "A challenging new assignment" },
    { "word": "assistant", "phrase": "My assistant will handle it." },
    { "word": "associate", "phrase": "A business associate" },
    { "word": "atmosphere", "phrase": "A relaxed work atmosphere" },
    { "word": "auction", "phrase": "An online auction" },
    { "word": "auditorium", "phrase": "The main auditorium" },
    { "word": "author", "phrase": "The author of the report" },
    { "word": "automobile", "phrase": "The automobile industry" },
    { "word": "avenue", "phrase": "Another avenue to explore" },
    { "word": "backpack", "phrase": "His backpack was stolen." },
    { "word": "badge", "phrase": "Please wear your security badge." },
    { "word": "baggage", "phrase": "Excess baggage fee" },
    { "word": "ballroom", "phrase": "The grand ballroom" },
    { "word": "banquet", "phrase": "The annual banquet" },
    { "word": "basis", "phrase": "On a regular basis" },
    { "word": "belonging", "phrase": "Personal belongings" },
    { "word": "alert", "phrase": "A severe weather alert" },
    { "word": "amaze", "phrase": "The results will amaze you." },
    { "word": "announce", "phrase": "We are pleased to announce." },
    { "word": "anticipate", "phrase": "We anticipate high demand." },
    { "word": "apologize", "phrase": "I must apologize for the delay." },
    { "word": "appeal", "phrase": "The product's broad appeal" },
    { "word": "apply", "phrase": "Apply the new policy." },
    { "word": "appoint", "phrase": "We will appoint a new director." },
    { "word": "appreciate", "phrase": "We appreciate your patience." },
    { "word": "approve", "phrase": "The board must approve it." },
    { "word": "arrange", "phrase": "I'll arrange the meeting." },
    { "word": "assemble", "phrase": "Assemble the team at 9 AM." },
    { "word": "assure", "phrase": "I assure you, it's fine." },
    { "word": "attach", "phrase": "Please attach the file." },
    { "word": "attempt", "phrase": "Another attempt was made." },
    { "word": "attend", "phrase": "Will you attend the seminar?" },
    { "word": "attract", "phrase": "Attract new customers." },
    { "word": "attribute", "phrase": "We attribute our success to teamwork." },
    { "word": "authorize", "phrase": "I cannot authorize that." },
    { "word": "award", "phrase": "Win an industry award." },
    { "word": "able", "phrase": "We are able to proceed." },
    { "word": "aboard", "phrase": "Welcome aboard the team." },
    { "word": "absolutely", "phrase": "That is absolutely correct." },
    { "word": "academic", "phrase": "Academic qualifications" },
    { "word": "acclaimed", "phrase": "An acclaimed professional" },
    { "word": "accordingly", "phrase": "We acted accordingly." },
    { "word": "accurate", "phrase": "Ensure the data is accurate." },
    { "word": "active", "phrase": "An active member" },
    { "word": "actual", "phrase": "The actual cost was higher." },
    { "word": "additionally", "phrase": "Additionally, we recommend..." },
    { "word": "adjacent", "phrase": "The adjacent building" },
    { "word": "administrative", "phrase": "Administrative duties" },
    { "word": "afterward", "phrase": "We can discuss it afterward." },
    { "word": "alongside", "phrase": "Work alongside experts." },
    { "word": "alternative", "phrase": "An alternative solution" },
    { "word": "amateur", "phrase": "An amateur photographer" },
    { "word": "annual", "phrase": "The annual report" },
    { "word": "approximately", "phrase": "Approximately 50 people attended." },
    { "word": "architectural", "phrase": "Architectural design" },
    { "word": "aside", "phrase": "All jokes aside" }
  
]